name: module_home
description: A new Flutter package project.
version: 0.0.1
homepage: g

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  commons:
    git:
      url: https://github.com/toshiossada/microapp_commons.git
      ref: v1.0.0  
  commons_dependencies:
    git:
      url: https://github.com/toshiossada/microapp_commons_dependencies.git
      ref: v1.0.0
  module_home_domain:
    path: '../module_home_domain'      
  module_home_infra:
    path: '../module_home_infra'
  module_home_presenter:
    path: '../module_home_presenter'

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  flutter_modular_test: ^1.0.1
  hive_generator: ^1.1.0
  http_mock_adapter: ^0.2.1
  mockito: ^5.0.5
  triple_test: ^0.0.5  
  effective_dart: ^1.3.1    

flutter:
